apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: vote-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: vote-app
  template:
    ref: vote-app
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret 
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: olajideoluwatoosin
  secretToken: "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"
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github-secret
# type: Opaque
# stringData:
#   secretToken: "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"
